# Idea is this file could be autogenerated form a linux variant or vica versa. 

alias gits='git  status '
alias gitl='git log --oneline --decorate'

alias gitcl='git clean -n'

# list ignored files. Otere ways of doing this
alias gitig='git status --short --ignored'
